### ISSUE TITLE
Extension doesn't work anymore with Firefox 57

### ISSUE THREAD

**Issue by modir** [smoqadam/add-to-feedly#2]
This extension doesn't work with Firefox 57 anymore.
More information about this here on the Mozilla website:
https://support.mozilla.org/en-US/kb/firefox-add-technology-modernizing?as=u&utm_source=inproduct

**Comment by smoqadam** [comment]
thanks for your report,

Now you can use it with Firefox 57 https://addons.mozilla.org/addon/add-to-feedly/
